[workspace]
members = ["templates/*"]

[package]
name = "micro-games-kit"
version = "0.20.0"
edition = "2021"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
description = "Micro Games Kit"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/micro-games-kit"
repository = "https://github.com/PsichiX/micro-games-kit"
documentation = "https://docs.rs/micro-games-kit"
readme = "README.md"
exclude = ["resources/", "templates/"]

[dependencies]
spitfire-core = "0.26"
spitfire-glow = "0.26"
spitfire-fontdue = "0.26"
spitfire-draw = "0.26"
spitfire-input = "0.26"
spitfire-gui = "0.26"
raui-core = "0.61"
raui-immediate = "0.61"
raui-immediate-widgets = "0.61"
emergent = "1.7"
typid = "1"
image = "0.24"
fontdue = "0.8"
vek = "0.16"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
noise = "0.8"
rand = "0.8"
kira = "0.8"

[target.'cfg(target_arch = "wasm32")'.dependencies]
winit = "0.26"
instant = { version = "0.1", features = ["wasm-bindgen"] }
getrandom = { version = "0.2", features = ["js"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glutin = "0.28"
